id: test_superapp_error
title: Возвращаем ошибку из superapp

source:
    request:
        method: get
        headers:
            X-YaTaxi-User: 'eats_user_id=id1'
            X-Request-Application: 'app_info=ab3'
    expectations:
        response:
            status-code: 404
            body:
                source: 'core'
                iam: 'some_err'

mocks:
  - resource: eda-superapp-tracking
    response:
        status-code: 404
        body:
            iam: 'some_err'
    expectations:
        call-count: 1

experiments:
    values:
        use_eats_orders_tracking_service:
            source: 'core'
            mirror: ''
