id: test_tpp_error
title: Возвращаем ошибку из Tracking++

source:
    request:
        method: get
        headers:
            X-YaTaxi-User: 'eats_user_id=id1'
            X-Request-Application: 'app_info=ab3'
    expectations:
        response:
            status-code: 404
            body:
                source: 'tracking++'
                iam: 'some_err'

mocks:
  - resource: eats-orders-tracking
    response:
        status-code: 404
        body:
            iam: 'some_err'
    expectations:
        call-count: 1

experiments:
    values:
        use_eats_orders_tracking_service:
            source: 'eats-orders-tracking'
            mirror: ''
